project_name: cloudflare-ddns
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/cloudflare-ddns/main.go
  binary: cloudflare-ddns
  ldflags: |
        -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: nenad
    name: cloudflare-ddns
  prerelease: auto
