version: 2.1
orbs:
  golangci-lint: timakin/golangci-lint@0.1.1
jobs:
  run-tests:
    docker:
      - image: golang:latest

    working_directory: /cloudflare-ddns
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v -race ./...
workflows:
  build:
    jobs:
      - run-tests
      - golangci-lint/lint
