version: 2.1
orbs:
  golangci-lint: timakin/golangci-lint@0.1.1
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: /cloudflare-ddns
    steps:
      - checkout
      - run: GOOS=linux GOARCH=amd64 make build
      - run: tar --gzip --create -f cloudflare-ddns-linux-x86.tar.gz cloudflare-ddns
      - store_artifacts:
          path: /cloudflare-ddns/cloudflare-ddns-linux-x86.tar.gz

  run-tests:
    docker:
      - image: golang:latest

    working_directory: /cloudflare-ddns
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v -race ./...
workflows:
  build:
    jobs:
      - run-tests
      - golangci-lint/lint
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
